all:
  hosts:
    manager:
      ansible_host: 10.19.110.80
      ansible_private_key_file: /home/lmadsen/.ssh/halabdot7
      ansible_user: cloud-user
      password_file: engine.yml
    virthost:
      ansible_host: 10.19.110.7
      ansible_private_key_file: /home/lmadsen/.ssh/id_rsa
      ansible_user: root
      password_file: virthost.yml
  children:
    virthosts:
      hosts:
        manager:
        virthost:
    engine:
      hosts:
        manager:
# vim: set tabstop=2 shiftwidth=2 smartindent expandtab :
