---
- name: Create a template from qcow
  hosts: engine
  #  connection: local
  gather_facts: false

  vars_files:
    - ../vars/{{ password_file }}

  vars:
    engine_url: https://engine.dev.nfvpe.site/ovirt-engine/api
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    qcow_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2
    template_cluster: Default
    template_name: centos7_template
    template_memory: 4GiB
    template_cpu: 2
    template_disk_size: 10GiB
    template_disk_storage: data

  roles:
    - oVirt.image-template
