---
- name: Setup RHV
  hosts: engine
  become: true
  become_user: root
  vars_files:
    # Contains encrypted `ovirt_engine_setup_admin_password` variable using ansible-vault
    - ../vars/passwords.yml
  vars:
    ovirt_engine_setup_version: '4.2'
    ovirt_engine_setup_organization: 'dev.nfvpe.site'
    ovirt_engine_setup_product_type: 'rhv'

  tasks:
    - name: Install dependencies
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - firewalld
          - java-1.8.0-openjdk-headless

    - name: Install engine
      include_role:
        name: oVirt.engine-setup
