---
- name: oVirt infra
  hosts: engine
  #  connection: local
  gather_facts: false

  vars_files:
    # Contains encrypted `engine_password` variable using ansible-vault
    - ../vars/{{ password_file }}

  vars:
    vm_state: running
    wait_for_ip: yes

    engine_url: https://engine.dev.nfvpe.site/ovirt-engine/api
    engine_user: admin@internal
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    openshift_node:
      cluster: Default
      domain: dev.nfvpe.site
      template: rhel7_template
      memory: 16GiB
      cores: 2
      state: "{{ vm_state }}"
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDW5OI/o+gZm8k216iTbnkv5pJnGJfOJ8yMYrJ8c6pYia8ZwkUtFWj/3LzNWO2r/XiMCV9eOfUo8By1adb9WNgWH8fIhT3QwE60nX6HGilbW3EWVJF7WrHeodZJ4oFHzjGr/pmSsTL3lEbw/+ghHD1CrVMmNAuluaU7U9meY2S9iWAcI/5VMQBkyfqOA5uwMmDdBMVw+sS5oRrCKJ1sNqKosnRBmD7V6HvTgkxrmOgHzcxmU4jLN0rur4YCNJDUBZf+ZroHFDRJBwqu6QBqMxc+mzePwE/VAmhaf55Q8w15/Km+ilUcWgoZiYoqIWRLvfSqHbAWhCiqJW9av6YuY8aH lmadsen@rover.home.ljam.me
      disks:
        - size: 20GiB
          name: data
          storage_domain: data
          interface: virtio
      nics:
        - name: ovirtmgmt
          network: ovirtmgmt
          profile: ovirtmgmt

    vms:
      - name: openshift-master
        tag: openshift_node
        profile: "{{ openshift_node }}"
        cloud_init:
          host_name: openshift-master.dev.nfvpe.site
          nic_ip_address: 10.19.111.101
          root_password: redhat
          dns_servers: 10.19.110.9
          dns_search: dev.nfvpe.site
          nic_boot_protocol: static
          nic_netmask: 255.255.255.0
          nic_gateway: 10.19.111.254
          nic_on_boot: true
          nic_name: eth0
      - name: openshift-node-1
        tag: openshift_node
        profile: "{{ openshift_node }}"
        cloud_init:
          host_name: openshift-node-1.dev.nfvpe.site
          nic_ip_address: 10.19.111.102
          root_password: redhat
          dns_servers: 10.19.110.9
          dns_search: dev.nfvpe.site
          nic_boot_protocol: static
          nic_netmask: 255.255.255.0
          nic_gateway: 10.19.111.254
          nic_on_boot: true
          nic_name: eth0
      - name: openshift-node-2
        tag: openshift_node
        profile: "{{ openshift_node }}"
        cloud_init:
          host_name: openshift-node-2.dev.nfvpe.site
          nic_ip_address: 10.19.111.103
          root_password: redhat
          dns_servers: 10.19.110.9
          dns_search: dev.nfvpe.site
          nic_boot_protocol: static
          nic_netmask: 255.255.255.0
          nic_gateway: 10.19.111.254
          nic_on_boot: true
          nic_name: eth0

  roles:
    - oVirt.vm-infra
